user:
  vault:
    exists: true
    home: "{{vault_config_path}}"
    shell: "{{vault_user_shell}}"

group:
  vault:
    exists: true

file:
  "{{vault_bin_dest}}/vault":
    exists: true
    owner: root
    group: root
    filetype: file

service:
  vault:
    enabled: true
    running: true