# goss bin location
goss_bin_src: https://github.com/aelsabbahy/goss/releases/latest/download/goss-linux-amd64
goss_bin_dest: /usr/local/bin/

# vault settings
vault_config_path: /etc/vault.d
vault_user_shell: /bin/false

# vault binary location
vault_bin_dest: /usr/local/bin/